//
//  PlayingCard.m
//  CardMatch
//
//  Created by Evan Knox on 2014-09-02.
//  Copyright (c) 2014 NaliApplications. All rights reserved.
//

#import "PlayingCard.h"

@implementation PlayingCard

-(NSString *)contents{
    NSArray *rankStrings = [PlayingCard rankStrings];
    return [rankStrings[self.rank] stringByAppendingString:self.suit];
    
}

@synthesize suit = _suit;//given we provide a setter and getter for suit

+(NSArray *)validSuits{
    return @[@"clubs",@"hearts",@"spades",@"diamonds"];
}
-(void)setSuit:(NSString *)suit{//ObjC autogenerated this, must be default setter method
    if([[PlayingCard validSuits] containsObject:suit])
    {//Need to get the actual symbols to be displayed
        suit = suit;//this line may break the code
    }
}
-(NSString *) suit{//getter for suit
    return _suit ? _suit : @"?";//no idea what that does, wierd syntax look at this later
}

+(NSArray *) rankStrings {
    return @[@"?",@"A",@"2",@"3",@"4",@"5",@"6",@"7",@"8",@"9",@"10",@"J",@"Q",@"K"];
}

+ (NSUInteger) maxRank {
    return [[self  rankStrings] count]-1;
}

- (void) setRank:(NSUInteger)rank{
    if (rank<=[PlayingCard maxRank]) {
        _rank=rank;
    }
}
@end